Version 1.0.1

diff --git a/git-bbflow-push b/git-bbflow-push
--- a/git-bbflow-push
+++ b/git-bbflow-push
@@ -1,4 +1,8 @@
 #
+# git-bbflow -- A collection of Git extensions to provide high-level
+# repository operations for Blue Billywig's branching model.
+#
+#
 # Copyright (c) 2012 Blue Billywig B.V. All rights reserved.
 #
 # Based on the work of Vincent Driessen, for which the copyright notice follows.
@@ -32,34 +36,43 @@
 # policies, either expressed or implied, of Vincent Driessen.
 #
 
-prefix=/usr/local
+require_git_repo
+require_gitbbflow_initialized
+gitbbflow_load_settings
 
-# files that need mode 755
-EXEC_FILES=git-bbflow
+usage() {
+	echo "usage: git bbflow push"
+}
 
-# files that need mode 644
-SCRIPT_FILES =git-bbflow-init
-SCRIPT_FILES+=git-bbflow-push
-SCRIPT_FILES+=git-bbflow-update
-SCRIPT_FILES+=git-bbflow-cleanup
-SCRIPT_FILES+=git-bbflow-feature
-SCRIPT_FILES+=git-bbflow-hotfix
-SCRIPT_FILES+=git-bbflow-release
-SCRIPT_FILES+=git-bbflow-version
-SCRIPT_FILES+=gitbbflow-common
-SCRIPT_FILES+=gitbbflow-shFlags
+cmd_default() {
+    git_fetch_origin
+    require_clean_working_tree
 
-all:
-	@echo "usage: make install"
-	@echo "       make uninstall"
+    BRANCH=$(git_current_branch)
 
-install:
-	@test -f gitbbflow-shFlags || (echo "Run 'git submodule init && git submodule update' first." ; exit 1 )
-	install -d -m 0755 $(prefix)/bin
-	install -m 0755 $(EXEC_FILES) $(prefix)/bin
-	install -m 0644 $(SCRIPT_FILES) $(prefix)/bin
+    [ "$BRANCH" != "$DEVELOP_BRANCH" ] || die "Pushing the $DEVELOP_BRANCH branch is done automatically on 'git bbflow feature complete'."
+    [ "$BRANCH" != "$MASTER_BRANCH" ] || die "Pushing the $MASTER_BRANCH branch is done automatically on 'git bbflow release complete'."
 
-uninstall:
-	test -d $(prefix)/bin && \
-	cd $(prefix)/bin && \
-	rm -f $(EXEC_FILES) $(SCRIPT_FILES)
+    local feature_branch=$(echo "$BRANCH" | grep "^$FEATURE_PREFIX")
+    local release_branch=$(echo "$BRANCH" | grep "^$RELEASE_PREFIX")
+    local hotfix_branch=$(echo "$BRANCH" | grep "^$HOTFIX_PREFIX")
+
+    [ ! -z "$feature_branch" -o ! -z "$release_branch" -o ! -z "$hotfix_branch" ] || die "Cannot push unsupported $BRANCH branch."
+
+    git_compare_branches "$BRANCH" "$ORIGIN/$BRANCH"
+    local status=$?
+    [ $status -ne 0 ] || die "Remote already up-to-date. Nothing to push."
+    [ $status -ne 1 ] || die "Remote already up-to-date, but local branch needs to be updated from remote. Use 'git bbflow update'."
+    [ $status -ne 3 ] || die "Local branch needs to be updated from remote first. Use 'git bbflow update'."
+    [ $status -ne 4 ] || die "Local and remote branches are not related. Unrecoverable error."
+
+    git push "$ORIGIN" "$BRANCH"
+
+    echo
+    echo "Pushed changes to remote '$ORIGIN'."
+}
+
+cmd_help() {
+	usage
+	exit 0
+}
diff --git a/gitbbflow-common b/gitbbflow-common
--- a/gitbbflow-common
+++ b/gitbbflow-common
@@ -45,13 +45,13 @@ warn() { echo "$@" >&2; }
 die() { warn "$@"; exit 1; }
 
 escape() {
-	echo "$1" | sed 's/\([\.\$\*]\)/\\\1/g'
+    echo "$1" | sed 's/\([\.\$\*]\)/\\\1/g'
 }
 
 # set logic
 has() {
-	local item=$1; shift
-	echo " $@ " | grep -q " $(escape $item) "
+    local item=$1; shift
+    echo " $@ " | grep -q " $(escape $item) "
 }
 
 # basic math
@@ -70,43 +70,84 @@ noflag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -ne $FLAGS_TRUE ]; }
 # Git specific common functionality
 #
 
-git_local_branches() { git branch --no-color | sed 's/^[* ] //'; }
-git_remote_branches() { git branch -r --no-color | sed 's/^[* ] //'; }
-git_all_branches() { ( git branch --no-color; git branch -r --no-color) | sed 's/^[* ] //'; }
-git_all_tags() { git tag; }
+git_fetch_origin() {
+    git fetch -q -p "$ORIGIN" || die "Could not fetch from '$ORIGIN'."
+}
+
+git_local_branches() {
+    git branch --no-color | sed 's/^[* ] //'
+}
+
+git_remote_branches() {
+    git branch -r --no-color | sed 's/^[* ] //'
+}
+
+git_all_branches() {
+    git_local_branches
+    git_remote_branches
+}
+
+git_merged_branches() {
+    local subject=$1
+    git branch --no-color --merged $subject | sed 's/^[* ] //'
+}
+
+git_all_tags() {
+    git tag
+}
 
 git_current_branch() {
-	git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
+    git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
 }
 
 git_is_clean_working_tree() {
-	if ! git diff --no-ext-diff --ignore-submodules --quiet --exit-code; then
-		return 1
-	elif ! git diff-index --cached --quiet --ignore-submodules HEAD --; then
-		return 2
-	else
-		return 0
-	fi
+    if ! git diff --no-ext-diff --ignore-submodules --quiet --exit-code; then
+        return 1
+    elif ! git diff-index --cached --quiet --ignore-submodules HEAD --; then
+        return 2
+    else
+        return 0
+    fi
 }
 
 git_repo_is_headless() {
-	! git rev-parse --quiet --verify HEAD >/dev/null 2>&1
+    ! git rev-parse --quiet --verify HEAD >/dev/null 2>&1
 }
 
 git_local_branch_exists() {
-	has $1 $(git_local_branches)
+    has $1 $(git_local_branches)
 }
 
 git_remote_branch_exists() {
-	has $1 $(git_remote_branches)
+    has $1 $(git_remote_branches)
 }
 
 git_branch_exists() {
-	has $1 $(git_all_branches)
+    has $1 $(git_all_branches)
 }
 
 git_tag_exists() {
-	has $1 $(git_all_tags)
+    has $1 $(git_all_tags)
+}
+
+git_update_from_origin() {
+    local current_branch=$(git_current_branch)
+    git_compare_branches "$current_branch" "$ORIGIN/$current_branch"
+    local status=$?
+    if [ $status -eq 1 ]; then
+        git merge "$ORIGIN/$current_branch"
+    elif [ $status -eq 3 ]; then
+        git merge "$ORIGIN/$current_branch"
+    fi
+}
+
+git_push_to_origin() {
+    local current_branch=$(git_current_branch)
+    git_compare_branches "$current_branch" "$ORIGIN/$current_branch"
+    local status=$?
+    if [ $status -eq 2 ]; then
+        git push $ORIGIN "$current_branch"
+    fi
 }
 
 #
@@ -122,22 +163,22 @@ git_tag_exists() {
 # 4    There is no merge base, i.e. the branches have no common ancestors
 #
 git_compare_branches() {
-	local commit1=$(git rev-parse "$1")
-	local commit2=$(git rev-parse "$2")
-	if [ "$commit1" != "$commit2" ]; then
-		local base=$(git merge-base "$commit1" "$commit2")
-		if [ $? -ne 0 ]; then
-			return 4
-		elif [ "$commit1" = "$base" ]; then
-			return 1
-		elif [ "$commit2" = "$base" ]; then
-			return 2
-		else
-			return 3
-		fi
-	else
-		return 0
-	fi
+    local commit1=$(git rev-parse "$1")
+    local commit2=$(git rev-parse "$2")
+    if [ "$commit1" != "$commit2" ]; then
+        local base=$(git merge-base "$commit1" "$commit2")
+        if [ $? -ne 0 ]; then
+            return 4
+        elif [ "$commit1" = "$base" ]; then
+            return 1
+        elif [ "$commit2" = "$base" ]; then
+            return 2
+        else
+            return 3
+        fi
+    else
+        return 0
+    fi
 }
 
 #
@@ -146,10 +187,46 @@ git_compare_branches() {
 # Checks whether branch $1 is succesfully merged into $2
 #
 git_is_branch_merged_into() {
-	local subject=$1
-	local base=$2
-	local all_merges="$(git branch --no-color --contains $subject | sed 's/^[* ] //')"
-	has $base $all_merges
+    local subject=$1
+    local base=$2
+
+    local all_merges="$(git branch --no-color --contains $subject | sed 's/^[* ] //')"
+    if [ "$(git rev-parse $subject)" = "$(git rev-parse $base)" ]; then
+        all_merges=""
+    fi
+
+    has $base $all_merges
+}
+
+#
+# git_is_branch_partially_merged_into()
+#
+# Checks whether branch $1 is partially merged into $2
+#
+git_is_branch_partially_merged_into() {
+    local subject=$1
+    local base=$2
+    local merge_base="$(git merge-base $base $subject)"
+
+    [ ! -z "$merge_base" ] || die "Branch '$subject' has no common ancestor with branch '$base'."
+
+    local base_parents="$(git rev-list --first-parent $base)"
+    ! has $merge_base $base_parents
+}
+
+#
+# git_latest_merge()
+#
+# Get latest merge commit of subject branch merged into base branch.
+#
+git_latest_merge() {
+    local base=$1
+    local subject=$2
+    local merge_base="$(git merge-base $base $subject)"
+
+    [ ! -z "$merge_base" ] || die "Branch '$subject' has no common ancestor with branch '$base'."
+
+    git rev-list --parents --merges $base | awk '$3~/'"$merge_base"'/ {print $1}'
 }
 
 #
@@ -158,36 +235,43 @@ git_is_branch_merged_into() {
 
 # check if this repo has been inited for gitbbflow
 gitbbflow_has_master_configured() {
-	local master=$(git config --get gitbbflow.branch.master)
-	[ "$master" != "" ] && git_local_branch_exists "$master"
+    local master=$(git config --get gitbbflow.branch.master)
+    [ "$master" != "" ] && git_local_branch_exists "$master"
 }
 
 gitbbflow_has_develop_configured() {
-	local develop=$(git config --get gitbbflow.branch.develop)
-	[ "$develop" != "" ] && git_local_branch_exists "$develop"
+    local develop=$(git config --get gitbbflow.branch.develop)
+    [ "$develop" != "" ] && git_local_branch_exists "$develop"
 }
 
 gitbbflow_has_prefixes_configured() {
-	git config --get gitbbflow.prefix.feature >/dev/null 2>&1     && \
-	git config --get gitbbflow.prefix.release >/dev/null 2>&1     && \
-	git config --get gitbbflow.prefix.hotfix >/dev/null 2>&1      && \
-	git config --get gitbbflow.prefix.versiontag >/dev/null 2>&1
+    git config --get gitbbflow.prefix.feature >/dev/null 2>&1     && \
+    git config --get gitbbflow.prefix.release >/dev/null 2>&1     && \
+    git config --get gitbbflow.prefix.hotfix >/dev/null 2>&1      && \
+    git config --get gitbbflow.prefix.featuretag >/dev/null 2>&1  && \
+    git config --get gitbbflow.prefix.releasetag >/dev/null 2>&1
 }
 
 gitbbflow_is_initialized() {
-	gitbbflow_has_master_configured                    && \
-	gitbbflow_has_develop_configured                   && \
-	[ "$(git config --get gitbbflow.branch.master)" !=    \
-	  "$(git config --get gitbbflow.branch.develop)" ] && \
-	gitbbflow_has_prefixes_configured
+    gitbbflow_has_master_configured            && \
+    gitbbflow_has_develop_configured           && \
+    [ "$(git config --get gitbbflow.branch.master)" !=    \
+      "$(git config --get gitbbflow.branch.develop)" ] && \
+    gitbbflow_has_prefixes_configured
 }
 
 # loading settings that can be overridden using git config
 gitbbflow_load_settings() {
-	export DOT_GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
-	export MASTER_BRANCH=$(git config --get gitbbflow.branch.master)
-	export DEVELOP_BRANCH=$(git config --get gitbbflow.branch.develop)
-	export ORIGIN=$(git config --get gitbbflow.origin || echo origin)
+    export DOT_GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
+    export MASTER_BRANCH=$(git config --get gitbbflow.branch.master)
+    export DEVELOP_BRANCH=$(git config --get gitbbflow.branch.develop)
+    export ORIGIN=$(git config --get gitbbflow.origin || echo origin)
+    export FEATURE_PREFIX=$(git config --get gitbbflow.prefix.feature)
+    export RELEASE_PREFIX=$(git config --get gitbbflow.prefix.release)
+    export RELEASE_FEATURES_PREFIX=$(git config --get gitbbflow.prefix.releasefeatures)
+    export HOTFIX_PREFIX=$(git config --get gitbbflow.prefix.hotfix)
+    export FEATURETAG_PREFIX=$(git config --get gitbbflow.prefix.featuretag)
+    export RELEASETAG_PREFIX=$(git config --get gitbbflow.prefix.releasetag)
 }
 
 #
@@ -207,36 +291,36 @@ gitbbflow_load_settings() {
 # 2: Multiple matches found. These matches are written to stderr
 #
 gitbbflow_resolve_nameprefix() {
-	local name=$1
-	local prefix=$2
-	local matches
-	local num_matches
+    local name=$1
+    local prefix=$2
+    local matches
+    local num_matches
 
-	# first, check if there is a perfect match
-	if git_local_branch_exists "$prefix$name"; then
-		echo "$name"
-		return 0
-	fi
+    # first, check if there is a perfect match
+    if git_local_branch_exists "$prefix$name"; then
+        echo "$name"
+        return 0
+    fi
 
-	matches=$(echo "$(git_local_branches)" | grep "^$(escape "$prefix$name")")
-	num_matches=$(echo "$matches" | wc -l)
-	if [ -z "$matches" ]; then
-		# no prefix match, so take it literally
-		warn "No branch matches prefix '$name'"
-		return 1
-	else
-		if [ $num_matches -eq 1 ]; then
-			echo "${matches#$prefix}"
-			return 0
-		else
-			# multiple matches, cannot decide
-			warn "Multiple branches match prefix '$name':"
-			for match in $matches; do
-				warn "- $match"
-			done
-			return 2
-		fi
-	fi
+    matches=$(echo "$(git_local_branches)" | grep "^$(escape "$prefix$name")")
+    num_matches=$(echo "$matches" | wc -l)
+    if [ -z "$matches" ]; then
+        # no prefix match, so take it literally
+        warn "No branch matches prefix '$name'"
+        return 1
+    else
+        if [ $num_matches -eq 1 ]; then
+            echo "${matches#$prefix}"
+            return 0
+        else
+            # multiple matches, cannot decide
+            warn "Multiple branches match prefix '$name':"
+            for match in $matches; do
+                warn "- $match"
+            done
+            return 2
+        fi
+    fi
 }
 
 #
@@ -244,74 +328,110 @@ gitbbflow_resolve_nameprefix() {
 #
 
 require_git_repo() {
-	if ! git rev-parse --git-dir >/dev/null 2>&1; then
-		die "fatal: Not a git repository"
-	fi
+    if ! git rev-parse --git-dir >/dev/null 2>&1; then
+        die "fatal: Not a git repository"
+    fi
 }
 
 require_gitbbflow_initialized() {
-	if ! gitbbflow_is_initialized; then
-		die "fatal: Not a gitbbflow-enabled repo yet. Please run \"git bbflow init\" first."
-	fi
+    if ! gitbbflow_is_initialized; then
+        die "fatal: Not a gitbbflow-enabled repo yet. Please run \"git bbflow init\" first."
+    fi
 }
 
 require_clean_working_tree() {
-	git_is_clean_working_tree
-	local result=$?
-	if [ $result -eq 1 ]; then
-		die "fatal: Working tree contains unstaged changes. Aborting."
-	fi
-	if [ $result -eq 2 ]; then
-		die "fatal: Index contains uncommited changes. Aborting."
-	fi
+    git_is_clean_working_tree
+    local result=$?
+    if [ $result -eq 1 ]; then
+        die "fatal: Working tree contains unstaged changes. Aborting."
+    fi
+    if [ $result -eq 2 ]; then
+        die "fatal: Index contains uncommited changes. Aborting."
+    fi
 }
 
 require_local_branch() {
-	if ! git_local_branch_exists $1; then
-		die "fatal: Local branch '$1' does not exist and is required."
-	fi
+    if ! git_local_branch_exists $1; then
+        die "fatal: Local branch '$1' does not exist and is required."
+    fi
 }
 
 require_remote_branch() {
-	if ! has $1 $(git_remote_branches); then
-		die "Remote branch '$1' does not exist and is required."
-	fi
+    if ! has $1 $(git_remote_branches); then
+        die "Remote branch '$1' does not exist and is required."
+    fi
 }
 
 require_branch() {
-	if ! has $1 $(git_all_branches); then
-		die "Branch '$1' does not exist and is required."
-	fi
+    if ! has $1 $(git_all_branches); then
+        die "Branch '$1' does not exist and is required."
+    fi
 }
 
 require_branch_absent() {
-	if has $1 $(git_all_branches); then
-		die "Branch '$1' already exists. Pick another name."
-	fi
+    if has $1 $(git_all_branches); then
+        die "Branch '$1' already exists. Pick another name."
+    fi
 }
 
 require_tag_absent() {
-	for tag in $(git_all_tags); do
-		if [ "$1" = "$tag" ]; then
-			die "Tag '$1' already exists. Pick another name."
-		fi
-	done
+    for tag in $(git_all_tags); do
+        if [ "$1" = "$tag" ]; then
+            die "Tag '$1' already exists. Pick another name."
+        fi
+    done
 }
 
 require_branches_equal() {
-	require_local_branch "$1"
-	require_remote_branch "$2"
-	git_compare_branches "$1" "$2"
-	local status=$?
-	if [ $status -gt 0 ]; then
-		warn "Branches '$1' and '$2' have diverged."
-		if [ $status -eq 1 ]; then
-			die "And branch '$1' may be fast-forwarded."
-		elif [ $status -eq 2 ]; then
-			# Warn here, since there is no harm in being ahead
-			warn "And local branch '$1' is ahead of '$2'."
-		else
-			die "Branches need merging first."
-		fi
-	fi
+    require_local_branch "$1"
+    require_remote_branch "$2"
+    git_compare_branches "$1" "$2"
+    local status=$?
+    if [ $status -gt 0 ]; then
+        warn "Branches '$1' and '$2' have diverged."
+        if [ $status -eq 1 ]; then
+            die "And branch '$1' may be fast-forwarded."
+        elif [ $status -eq 2 ]; then
+            # Warn here, since there is no harm in being ahead
+            warn "And local branch '$1' is ahead of '$2'."
+        else
+            die "Branches need merging first."
+        fi
+    fi
+}
+
+require_branch_uptodate() {
+    local branch=$1;
+    if [ -z "$branch" ]; then
+        branch=$(git_current_branch)
+    fi
+
+    require_local_branch "$branch"
+    require_remote_branch "$ORIGIN/$branch"
+    git_compare_branches "$branch" "$ORIGIN/$branch"
+    local status=$?
+    if [ $status -eq 1 ]; then
+        die "Branch '$branch' is not up-to-date. Update first with 'git bbflow $SUBCOMMAND update'."
+    elif [ $status -eq 3 ]; then
+        die "Branch '$branch' is not up-to-date and needs merging. Update first with 'git bbflow $SUBCOMMAND update'."
+    elif [ $status -eq 4 ]; then
+        die "Branch '$branch' has no common ancestor with '$ORIGIN'. How did this happen?"
+    fi
+}
+
+require_remote_uptodate() {
+    local branch=$1;
+    if [ -z "$branch" ]; then
+        branch=$(git_current_branch)
+    fi
+
+    require_local_branch "$branch"
+    require_remote_branch "$ORIGIN/$branch"
+    git_compare_branches "$branch" "$ORIGIN/$branch"
+    local status=$?
+    if [ $status -eq 2 ]; then
+        die "Branch '$branch' is yet pushed to '$ORIGIN'. Push first with 'git bbflow $SUBCOMMAND push'."
+    elif [ $status -eq 4 ]; then
+        die "Branch '$branch' has no common ancestor with '$ORIGIN'. How did this happen?"
+    fi
 }
