#1 Added developer and admin roles.

diff --git a/git-bbflow-init b/git-bbflow-init
--- a/git-bbflow-init
+++ b/git-bbflow-init
@@ -228,9 +228,10 @@ cmd_default() {
 	   ! git config --get gitbbflow.prefix.release >/dev/null 2>&1 ||
 	   ! git config --get gitbbflow.prefix.hotfix >/dev/null 2>&1 ||
 	   ! git config --get gitbbflow.prefix.featuretag >/dev/null 2>&1 ||
-	   ! git config --get gitbbflow.prefix.releasetag >/dev/null 2>&1; then
+	   ! git config --get gitbbflow.prefix.releasetag >/dev/null 2>&1 ||
+	   ! git config --get gitbbflow.role >/dev/null 2>&1; then
 		echo
-		echo "How to name your supporting branch prefixes?"
+		echo "How to name your supporting branches, prefixes and roles?"
 	fi
 
 	local prefix
@@ -301,6 +302,27 @@ cmd_default() {
 		fi
 		[ "$answer" = "-" ] && prefix= || prefix=${answer:-$default_suggestion}
 		git config gitbbflow.prefix.releasetag "$prefix"
+	fi
+
+	# Role
+	if ! git config --get gitbbflow.role >/dev/null 2>&1 || flag force; then
+	    default_suggestion=$(git config --get gitbbflow.role || echo "developer")
+	    while (true); do
+            echo -n "User role? <developer|admin> [$default_suggestion] "
+            if noflag defaults; then
+                read answer
+            else
+                echo
+            fi
+
+            local role=${answer:-$default_suggestion}
+            if [ "$role" = "developer" -o "$role" = "admin" ]; then
+                git config gitbbflow.role "$role"
+                break
+            fi
+
+            echo "Invalid role '$role'. Choose one of 'developer' or 'admin'."
+	    done
 	fi
 }
 
